### PR TITLE
v2.007: mastered

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey Pablo,

We've improved the Vietnamese and done some mastering.

Cheers,
Marc

### CODE REVIEW

**Comment by m4rc1e** [comment]
ping @impallari

**Comment by impallari** [comment]
Hi, I will review this today, before mergin

**Comment by impallari** [comment]
Ok, I accepted the merge, but there are still issues to be fixed, so it's not ready for public release
screeny-video-2-11-2016-14 56 30

**Comment by m4rc1e** [comment]
ping @davelab6

**Comment by davelab6** [comment]
@m4rc1e i have contracted pablo to make dosis great again

**Comment by m4rc1e** [comment]
For updates on this pr, see the source repo's issues: https://github.com/impallari/Dosis/issues

We have some to iron out first.

**Pull request merged**
